// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukouxthzfkjbodswhfbp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrb3V4dGh6ZmtqYm9kc3doZmJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MzkzNDgsImV4cCI6MjA3MTExNTM0OH0.Uq-bl7qMx2LkT7ejrubjO-PSoPmuaNNKWkmPgn64ya0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});